springdoc:
  version: 1.0.0-SNAPSHOT
  swagger-ui:
    use-root-path: true
spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    url : jdbc:postgresql://ec2-54-225-234-165.compute-1.amazonaws.com:5432/dd8cer0sor2gi0
    username : zjioblrqguksdq
    password : d9c89d57b0c728ea0b3706787dee486cd55c8cd91096248a8b0eb00ea671217f
    hikari :
      connectionTimeout : 30000
      maxLifetime : 1800000
      maximumPoolSize : 5
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        check_nullability : true
        temp:
          use_jdbc_metadata_defaults: false
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always